### ISSUE TITLE
AppImage missing for latest release

### ISSUE THREAD

**Issue by probonopd** [cjdenio/playbox#5]
Thanks for providing AppImages. However it is missing for the latest release.

**Comment by cjdenio** [comment]
Thank you for mentioning this! Soon, I hope to setup a Linux VM (my SSD doesn't have enough storage) to create Linux builds more often.
I just built an AppImage and a Debian package [here](https://github.com/cjdenio/playbox/releases/latest).

**Comment by probonopd** [comment]
Hi @cjdenio maybe you would like to check out https://travis-ci.com. You can build things in the cloud without needing a local machine. Many projects use it to build AppImages. A GitHub search will show you how to do it. Thanks!

**Comment by cjdenio** [comment]
I actually just started using Travis, but I haven't really done anything with it (except for creating a super-official "build: passing" badge) Thank you for suggesting this!
